n1 = input('Digite um número para ser somado: ')
n2 = input('Digite outro número para ser somado: ')
soma = int(n1) + int(n2)
subtração = int(n1) - int(n2)
multiplicação = int(n1) * int(n2)
divisão =  int(n1) / int(n2)
print('A soma dos números escolhidos é: ' + str(soma))
print('A subtração dos números escolhidos é: ' + str(subtração))
print('A multiplicação dos números escolhidos é: ' + str(multiplicação))
print('A divisão dos números escolhidos é: ' + str(divisão))